import type { Metadata } from "next";
import { Geist_Mono, Public_Sans } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

// Import css
import "@radix-ui/themes/styles.css";
import "./globals.css";

import { Theme } from "@radix-ui/themes";
import Link from "next/link";

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  post,
}: Readonly<{
  children: React.ReactNode;
  post: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${publicSans.variable} ${geistMono.variable} antialiased`}
        >
          <Theme appearance="dark" accentColor="mint" radius="full">
            <nav>
              <Link href="/post">Open modal</Link>
            </nav>
            <div>{post}</div>
            <div>{children}</div>

            {/*{modal}
            {children}*/}
          </Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
